name: Generate Metrics

on:
  schedule:
    - cron: '0 */12 * * *'  # Every 12 hours
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: lowlighter/metrics@latest
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
        # Options
        user: maslinedwin
        template: classic
        base: header, activity, community, repositories, metadata
        config_timezone: America/New_York
        
        # Features
        plugin_lines: yes
        plugin_topics: yes
        plugin_topics_mode: starred
        plugin_topics_sort: stars
        plugin_topics_limit: 15
        
        # Language stats
        plugin_languages: yes
        plugin_languages_analysis_timeout: 15
        plugin_languages_categories: markup, programming
        plugin_languages_colors: github
        plugin_languages_limit: 8
        plugin_languages_recent_categories: markup, programming
        plugin_languages_recent_days: 14
        plugin_languages_recent_load: 300
        plugin_languages_sections: most-used
        plugin_languages_threshold: 0%
        
        # Activity
        plugin_activity: yes
        plugin_activity_days: 14
        plugin_activity_filter: all
        plugin_activity_limit: 5
        plugin_activity_load: 300
        plugin_activity_visibility: all
        
        # Notable contributions
        plugin_notable: yes
        plugin_notable_from: organization
        plugin_notable_types: commit
        
        # Achievements
        plugin_achievements: yes
        plugin_achievements_threshold: C
        plugin_achievements_secrets: yes
        plugin_achievements_display: detailed
        plugin_achievements_limit: 0
        
        # Code frequency
        plugin_code: yes
        plugin_code_days: 3
        plugin_code_lines: 12
        plugin_code_load: 400
        plugin_code_visibility: public
        
        # Follow-up issues and PRs
        plugin_followup: yes
        plugin_followup_sections: repositories
        
        # People
        plugin_people: yes
        plugin_people_limit: 24
        plugin_people_identicons: no
        plugin_people_thanks: yes
        plugin_people_sponsors: no
        plugin_people_size: 28
        plugin_people_types: followers, following
        
        # Stargazers
        plugin_stargazers: yes
        plugin_stargazers_charts: yes
        plugin_stargazers_charts_type: classic
        
        # Stars
        plugin_stars: yes
        plugin_stars_limit: 4